name: Testing matrix strategy
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  deploy:
    if: ${{contains(github.ref, 'refs/heads/master')}}
    runs-on: ubuntu-latest
    steps:
    -  run:  echo "Depolying on branch ${{github.ref}}"
