name: Testing matrix strategy
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  debugging:
    runs-on: ubuntu-latest
    steps:
    -  run: |
        echo "::warning file=app.js, line=10, endline=22::Missing a semicolon"
        echo "::error file=app.js, line=23, endline=32, title=On Handle Error::Error in app.js"
