name: Testing matrix strategy
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  deploy:
    if: ${{github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest
    steps:
    -  run:  echo "Deploying branch ${{ github.ref }}"
