name: Testing
on: 
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    test_1:
        runs-on: ubuntu-latest
        steps:
        -   name: "first testing"
            run: |
                echo "***1***"
                echo "FIRST JOB TESTING"
    test_2:
        runs-on: ubuntu-latest
        steps:
        -   name: "second testing"
            run: echo "SECOND JOB TESTING"
    