name: Testing matrix strategy
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  debugging:
    runs-on: ubuntu-latest
    steps:
    -  name: Set Color
       id: color-generator
       run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"

    -  name: Get Color
       run: echo "${{steps.color-generator.outpus.SELECTED_COLOR}}"
        
